feat(google_secret): Add google secret manager handler
JanssenProject/jans-pycloudlib pull request #6
Opened 2021-02-23 13:29 UTC by moabu

This PR adds the ability to interact directly with google secret manager given the following is provided : 

Required Envs: 

`GOOGLE_PROJECT_ID` googles project id
`GOOGLE_APPLICATION_CREDENTIALS`  json file of service account that should be injected in upstream images

Optional Envs:
 
`CN_GOOGLE_SECRET_VERSION_ID` secrets version. Defaults to `latest`, which is recommended. 
`CN_GOOGLE_SECRET_MANAGER_PASSPHRASE` Any passphrase for encryption. This is recommended to be changed and defaults to `secret`
`CN_SECRET_GOOGLE_SECRET`. Prefix for secret in google secret manager. Defaults to `jans`. If left intact two secrets will be created `jans-secret` and `jans-configuration`. 

All other dependent images need to be updated to use this image. 
- Update `jans-pycloudlib` in `requirements.txt`
- Add `py3-grpcio` Alpine [package](https://pkgs.alpinelinux.org/package/edge/community/x86/py3-grpcio) to `DockerFile`. 

Example:

  ```DockerFile
     RUN apk update \
         && apk add --no-cache openssl py3-pip tini curl bash py3-grpcio openjdk11-jre-headless py3-cryptography \
         && apk add --no-cache --virtual build-deps wget git \
         && mkdir -p /usr/java/latest \
         && ln -sf /usr/lib/jvm/default-jvm/jre /usr/java/latest/jre
  ```
  
  unit tests has not been added to the initial commit.

2021-02-23 13:53 UTC, iromli requested changes

2021-02-23 13:53 UTC, iromli commented on jans/pycloudlib/secret/google_secret.py
> +    def set(self, key: str, value: Any, data: dict = None) -> bool:
This `set` method violates the base class method.

2021-02-23 13:53 UTC, iromli commented on jans/pycloudlib/manager.py
> +            self.adapter = GoogleSecret(configuration=True)
Use `jans.pycloudlib.config.google_config.GoogleConfig` class instead of `GoogleSecret`.

2021-02-23 13:53 UTC, iromli commented on jans/pycloudlib/secret/google_secret.py
> +        result = self.all()
Is it possible to get single value instead of all keys (and then pick one of them)?

2021-02-23 13:53 UTC, iromli commented on jans/pycloudlib/secret/google_secret.py
> +            print("Wrong passphrase used.")
Remove all `print` calls, use logging instead.

2021-02-23 18:33 UTC, iromli commented
@moabu As we have config and secret adapter layers, i proposed to split these envs:

```
- CN_GOOGLE_SECRET_VERSION_ID
- CN_GOOGLE_SECRET_MANAGER_PASSPHRASE
- CN_SECRET_GOOGLE_SECRET
```

into:

```
# config
- CN_CONFIG_GOOGLE_VERSION_ID (default to latest)
- CN_CONFIG_GOOGLE_MANAGER_PASSPHRASE (default to secret)
- CN_CONFIG_GOOGLE_PREFIX (default to jans)

# secret
- CN_SECRET_GOOGLE_VERSION_ID (default to latest)
- CN_SECRET_GOOGLE_MANAGER_PASSPHRASE (default to secret)
- CN_SECRET_GOOGLE_PREFIX (default to jans)
```

In future version, we may unify some of ENVs, but as for now we need to conform to existing pattern.

2021-02-24 06:55 UTC, moabu commented
@iromli `CN_GOOGLE_SECRET_MANAGER_PASSPHRASE` is exclusively used in secrets only as we use encryption there so I don't think we should change that. As for the others, to comply with the current design we can rename them.

`CN_SECRET_GOOGLE_SECRET_VERSION_ID`
`CN_SECRET_GOOGLE_SECRET_NAME_PREFIX`
---
`CN_CONFIG_GOOGLE_SECRET_VERSION_ID`
`CN_CONFIG_GOOGLE_SECRET_NAME_PREFIX`

2021-02-24 09:26 UTC, iromli commented
CN_GOOGLE_SECRET_MANAGER_PASSPHRASE should be renamed to CN_SECRET_GOOGLE_SECRET_MANAGER_PASSPHRASE

2021-02-24 09:29 UTC, iromli commented
@moabu Current design is any config adapter env is prefixed with CN_CONFIG, secret adapter env is prefixed with CN_SECRET

2021-02-24 10:25 UTC, moabu commented
sounds good. I think we need to re-think naming envs down the road. I'll post the change shortly.

2021-02-24 10:30 UTC, iromli commented
Yes, we can redesign the env after this PR get merged

2021-02-24 10:34 UTC, moabu commented
ok. Im investigating an issue , some config and secrets do not get pushed after yesterdays commits.

2021-02-24 13:04 UTC, moabu commented
This PR can be merged. All initial tests passed.

```bash
NAME                                READY   STATUS      RESTARTS   AGE
jans-config-7dtzv                   0/1     Completed   0          10m
jans-opendj-0                       1/1     Running     1          10m
jans-persistence-cft64              0/1     Completed   0          10m
jans-scim-5f6d969658-wnhg7          1/1     Running     2          10m
jans-fido2-565fdd4db4-f4k66         1/1     Running     3          10m
jans-client-api-758b6b5dff-j576k    1/1     Running     3          10m
jans-auth-server-5b9b67984d-kklmn   1/1     Running     2          10m
jans-config-api-7b8c54fc97-9k7t7    1/1     Running     3          10m
```

Upstream changes required : 

Upon deployment a service account must be mounted at the given path `GOOGLE_APPLICATION_CREDENTIALS ` . The service account attached upon deployment must have the permission `roles/secretmanager.admin`

Final remark: 

This PR adds the ability to interact directly with google secret manager given the following is provided : 

Required Envs: 

`GOOGLE_PROJECT_ID` googles project id
`GOOGLE_APPLICATION_CREDENTIALS`  json file of service account that should be injected in upstream images

Optional Envs:
 
#### Secret envs added

 `CN_SECRET_GOOGLE_SECRET_VERSION_ID`  secrets version. Defaults to `latest`, which is recommended. 
`CN_SECRET_GOOGLE_SECRET_MANAGER_PASSPHRASE` Any passphrase for encryption. This is recommended to be changed and defaults to `secret`
`CN_SECRET_GOOGLE_SECRET_NAME_PREFIX`. Prefix for secret in google secret manager. Defaults to `jans`. If left `jasn-secret` secret will be created.

#### Config envs added

 `CN_CONFIG_GOOGLE_SECRET_VERSION_ID`  secrets version. Defaults to `latest`, which is recommended. 
`CN_CONFIG_GOOGLE_SECRET_NAME_PREFIX`. Prefix for secret in google secret manager. Defaults to `jans`. If left intact `jans-configuration` secret will be created.


All other dependent images need to be updated to use this image. 
- Update `jans-pycloudlib` in `requirements.txt`
- Add `py3-grpcio` Alpine [package](https://pkgs.alpinelinux.org/package/edge/community/x86/py3-grpcio) to `DockerFile`. 
- Update READEME.md to include the above envs

Example:

  ```DockerFile
     RUN apk update \
         && apk add --no-cache openssl py3-pip tini curl bash py3-grpcio openjdk11-jre-headless py3-cryptography \
         && apk add --no-cache --virtual build-deps wget git \
         && mkdir -p /usr/java/latest \
         && ln -sf /usr/lib/jvm/default-jvm/jre /usr/java/latest/jre
  ```

2021-02-24 15:04 UTC, merged